export const data = JSON.parse("{\"key\":\"v-f5f52750\",\"path\":\"/posts/%E4%B8%AD%E9%97%B4%E4%BB%B6/rocketmq/%E6%8A%80%E6%9C%AF%E5%86%85%E5%B9%95.html\",\"title\":\"RocketMQ 内幕\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"RocketMQ 内幕\",\"icon\":\"fire\",\"category\":[\"RocketMQ\"],\"tag\":[\"技术内幕\"],\"description\":\"RocketMq技术内幕 1、rocketmq路由中心ns以及broker之间的联系 rocketmq集群一般是指broker的集群，每个br都会连接到NS上，br和ns是长连接，10s心跳， 生产者和消费者需要先从ns中获取到实际的broker才进行消息发送及消费。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/chenweiquan-red/posts/%E4%B8%AD%E9%97%B4%E4%BB%B6/rocketmq/%E6%8A%80%E6%9C%AF%E5%86%85%E5%B9%95.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"WQ-知识库\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"RocketMQ 内幕\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"RocketMq技术内幕 1、rocketmq路由中心ns以及broker之间的联系 rocketmq集群一般是指broker的集群，每个br都会连接到NS上，br和ns是长连接，10s心跳， 生产者和消费者需要先从ns中获取到实际的broker才进行消息发送及消费。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Durant\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"技术内幕\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"RocketMQ 内幕\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Durant\\\",\\\"url\\\":\\\"https://www.wqknowledge.top/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"RocketMq技术内幕\",\"slug\":\"rocketmq技术内幕\",\"link\":\"#rocketmq技术内幕\",\"children\":[{\"level\":3,\"title\":\"1、rocketmq路由中心ns以及broker之间的联系\",\"slug\":\"_1、rocketmq路由中心ns以及broker之间的联系\",\"link\":\"#_1、rocketmq路由中心ns以及broker之间的联系\",\"children\":[]},{\"level\":3,\"title\":\"2、rocketmq生产者问题\",\"slug\":\"_2、rocketmq生产者问题\",\"link\":\"#_2、rocketmq生产者问题\",\"children\":[]},{\"level\":3,\"title\":\"3、rocketmq底层文件存储\",\"slug\":\"_3、rocketmq底层文件存储\",\"link\":\"#_3、rocketmq底层文件存储\",\"children\":[]},{\"level\":3,\"title\":\"4、RocketMQ集群\",\"slug\":\"_4、rocketmq集群\",\"link\":\"#_4、rocketmq集群\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.82,\"words\":845},\"filePathRelative\":\"posts/中间件/rocketmq/技术内幕.md\",\"excerpt\":\"<h2> RocketMq技术内幕</h2>\\n<h3> 1、rocketmq路由中心ns以及broker之间的联系</h3>\\n<div class=\\\"language-text line-numbers-mode\\\" data-ext=\\\"text\\\"><pre class=\\\"language-text\\\"><code>    rocketmq集群一般是指broker的集群，每个br都会连接到NS上，br和ns是长连接，10s心跳，\\n    生产者和消费者需要先从ns中获取到实际的broker才进行消息发送及消费。\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
