export const data = JSON.parse("{\"key\":\"v-7a9c31a0\",\"path\":\"/posts/%E8%BF%90%E7%BB%B4/centos/centos%E7%BD%91%E7%BB%9C%E6%95%85%E9%9A%9C%E5%88%86%E6%9E%90.html\",\"title\":\"Centos 网络故障分析\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Centos 网络故障分析\",\"icon\":\"fire\",\"category\":[\"Centos\"],\"tag\":[\"Centos 网络\"],\"description\":\"1、认识network和NetworkManager 先说结论，在CentOS系统中，network服务和NetworkManager是两个常用的网络管理工具，它们之间有一定的关系，但是也有区别： network：network服务是在CentOS 6及更早版本中使用的传统网络管理方式。它使用 /etc/sysconfig/network-scripts/目录下的配置文件来管理网络接口和网络设置。 通过编辑这些配置文件，您可以手动配置网络接口、IP地址、网关、DNS等网络参数。 network服务提供了较为底层的网络管理功能，适用于服务器环境或不需要频繁变动网络配置的情况。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/%E8%BF%90%E7%BB%B4/centos/centos%E7%BD%91%E7%BB%9C%E6%95%85%E9%9A%9C%E5%88%86%E6%9E%90.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"博客演示\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Centos 网络故障分析\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1、认识network和NetworkManager 先说结论，在CentOS系统中，network服务和NetworkManager是两个常用的网络管理工具，它们之间有一定的关系，但是也有区别： network：network服务是在CentOS 6及更早版本中使用的传统网络管理方式。它使用 /etc/sysconfig/network-scripts/目录下的配置文件来管理网络接口和网络设置。 通过编辑这些配置文件，您可以手动配置网络接口、IP地址、网关、DNS等网络参数。 network服务提供了较为底层的网络管理功能，适用于服务器环境或不需要频繁变动网络配置的情况。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Centos 网络\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Centos 网络故障分析\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"1、认识network和NetworkManager\",\"slug\":\"_1、认识network和networkmanager\",\"link\":\"#_1、认识network和networkmanager\",\"children\":[]},{\"level\":3,\"title\":\"2、故障分析\",\"slug\":\"_2、故障分析\",\"link\":\"#_2、故障分析\",\"children\":[]}],\"readingTime\":{\"minutes\":2.05,\"words\":614},\"filePathRelative\":\"posts/运维/centos/centos网络故障分析.md\",\"excerpt\":\"<h3> 1、认识network和NetworkManager</h3>\\n<p>先说结论，在CentOS系统中，network服务和NetworkManager是两个常用的网络管理工具，它们之间有一定的关系，但是也有区别：</p>\\n<div class=\\\"language-textmate line-numbers-mode\\\" data-ext=\\\"textmate\\\"><pre class=\\\"language-textmate\\\"><code>network：network服务是在CentOS 6及更早版本中使用的传统网络管理方式。它使用\\n/etc/sysconfig/network-scripts/目录下的配置文件来管理网络接口和网络设置。\\n通过编辑这些配置文件，您可以手动配置网络接口、IP地址、网关、DNS等网络参数。\\nnetwork服务提供了较为底层的网络管理功能，适用于服务器环境或不需要频繁变动网络配置的情况。\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
