export const data = JSON.parse("{\"key\":\"v-23454630\",\"path\":\"/posts/%E4%B8%AD%E9%97%B4%E4%BB%B6/utility/Smart-doc.html\",\"title\":\"smart-doc\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"smart-doc\",\"icon\":\"fire\",\"category\":[\"utillity\"],\"tag\":[\"文档\"],\"description\":\"smart-doc是一个无侵入性的框架 1、简述 完全基于接口源码来分析生成接口文档，不采用任何注解侵入到业务代码中。你只需要按照 java-doc 标准编写注释， smart-doc 就能帮你生成一个简易明了的 markdown, html, doc, openai, postman, swagger, torna 等类型的文档。官方文档地址： https://smart-doc-group.github.io\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/chenweiquan-red/posts/%E4%B8%AD%E9%97%B4%E4%BB%B6/utility/Smart-doc.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"WQ-知识库\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"smart-doc\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"smart-doc是一个无侵入性的框架 1、简述 完全基于接口源码来分析生成接口文档，不采用任何注解侵入到业务代码中。你只需要按照 java-doc 标准编写注释， smart-doc 就能帮你生成一个简易明了的 markdown, html, doc, openai, postman, swagger, torna 等类型的文档。官方文档地址： https://smart-doc-group.github.io\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Durant\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"文档\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"smart-doc\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Durant\\\",\\\"url\\\":\\\"https://www.wqknowledge.top/\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"smart-doc是一个无侵入性的框架\",\"slug\":\"smart-doc是一个无侵入性的框架\",\"link\":\"#smart-doc是一个无侵入性的框架\",\"children\":[]},{\"level\":3,\"title\":\"1、简述\",\"slug\":\"_1、简述\",\"link\":\"#_1、简述\",\"children\":[]},{\"level\":3,\"title\":\"2、具体使用配置\",\"slug\":\"_2、具体使用配置\",\"link\":\"#_2、具体使用配置\",\"children\":[]},{\"level\":3,\"title\":\"3、使用技巧\",\"slug\":\"_3、使用技巧\",\"link\":\"#_3、使用技巧\",\"children\":[]},{\"level\":3,\"title\":\"部分html效果截图如下\",\"slug\":\"部分html效果截图如下\",\"link\":\"#部分html效果截图如下\",\"children\":[]}],\"readingTime\":{\"minutes\":7.03,\"words\":2108},\"filePathRelative\":\"posts/中间件/utility/Smart-doc.md\",\"excerpt\":\"<h3> smart-doc是一个无侵入性的框架</h3>\\n<h3> 1、简述</h3>\\n<p>完全基于接口源码来分析生成接口文档，不采用任何注解侵入到业务代码中。你只需要按照 java-doc 标准编写注释， smart-doc<br>\\n就能帮你生成一个简易明了的 markdown, html, doc, openai, postman, swagger, torna 等类型的文档。官方文档地址：<br>\\n<a href=\\\"https://smart-doc-group.github.io\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://smart-doc-group.github.io</a></p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
